run:
	bash setup.sh
	python3 TestCenter-master/testcenter.py -s soln -t test-cases -e --timeout 5
all:
	bash setup.sh
	python3 TestCenter-master/testcenter.py -s soln -t test-cases --timeout 5
verbose:
	bash setup.sh
	python3 TestCenter-master/testcenter.py -s soln -t test-cases -e -v --timeout 5
all-verbose:
	bash setup.sh
	python3 TestCenter-master/testcenter.py -s soln -t test-cases -v --timeout 5
